### PR TITLE
chore(deps): ugrade aedes-persistence to 9.1.1

### PR DESCRIPTION
**Pull request by seriousme**
This PR applies `aedes-persistence@9.0.3`.  While creating this it triggered me to *suggest* restructuring the class inheritance.
: https://github.com/moscajs/aedes-persistence-redis/pull/95#issuecomment-1120398605

I think the implementation of test.js in this PR indicates what it could look like if we restructure the class inheritance ;-)
Just to be sure: this PR does *not* restructure class inheritance ! 

Kind regards,
Hans

### CODE REVIEW

**Review by robertsLando — CHANGES_REQUESTED** [review]
Could you split this in two PR? One that only does the update (also remember to update ci matrix) and the other that implements the change you suggested about the inherit turn

**Comment by seriousme** [comment]
> Could you split this in two PR? One that only does the update (also remember to update ci matrix) and the other that implements the change you suggested about the inherit turn

The CI matrix was updated in https://github.com/moscajs/aedes-cached-persistence/pull/51 (I will rebase and resubmit ;-))

The only way to get the updated dependency to work is to update `test.js` as well as test.js was `borrowing` functionality from `aedes-persistence` in a way that does not work with the ES2015 classes used in 9.0.3. So I had to change stuff.

This does *not* change the class inheritance as I did not touch `persistence.js` it is just the test that has been changed.

Kind regards,
Hans

**Comment by seriousme** [comment]
Now this is weird:  the [error](https://github.com/moscajs/aedes-cached-persistence/runs/6355827145?check_suite_focus=true#step:5:2104) is: 

```
not ok 2049 should be deeply equivalent
  ---
    operator: deepEqual
    expected: |-
      [ { clientId: 'abcde', topic: 'hello/#', qos: 1, rh: 0, rap: true, nl: false } ]
    actual: |-
      [ { clientId: 'abcde', topic: 'hello/#', qos: 1 } ]
    at: <anonymous> (/home/runner/work/aedes-cached-persistence/aedes-cached-persistence/node_modules/aedes-persistence/abstract.js:457:13)
    stack: |-
      Error: should be deeply equivalent
```

However `aedes-persistence@9.0.3` as listed in package.json does not have any reference to `rh`,`rap` or `nl` as this was [only added today](https://github.com/moscajs/aedes-persistence/blame/798d068dd02521686ea67372d5e81f83ba4018eb/abstract.js#L457-L464).

Kind regards,
Hans
ps. I will see if I can make the tests work again against 9.1.1.

**Comment by seriousme** [comment]
9.1.1 requires qlobber 7.0.0.

**Review by robertsLando — APPROVED** [review]

**Comment by robertsLando** [comment]
> And just to be sure: this PR does not touch persistence.js. It only touches package.json and test.js

Yep sorry I was checking the changes after reading your other [comment](https://github.com/moscajs/aedes-persistence-redis/pull/95#issuecomment-1120398605). Changes looks good to me. Is it good to merge?

**Comment by seriousme** [comment]
> > And just to be sure: this PR does not touch persistence.js. It only touches package.json and test.js
> 
> Yep sorry I was checking the changes after reading your other [comment](https://github.com/moscajs/aedes-persistence-redis/pull/95#issuecomment-1120398605). Changes looks good to me. Is it good to merge?

Yes, should be good to go.

Kind regards,
Hans

**Comment by robertsLando** [comment]
@seriousme Seems there are some errors in types:

```
types/index.d.ts:82:2
  ✖  82:2  Property outgoingEnqueueCombi in type AedesCachedPersistence is not assignable to the same property in base type Pick<AedesPersistence, "createRetainedStreamCombi" | "subscriptionsByTopic" | "cleanSubscriptions" | "outgoingEnqueueCombi">.
  Type (sub: { clientId: string; }[], packet: AedesPacket, cb: (error: Error | null | undefined) => void) => void is not assignable to type (subs: { clientId: string | undefined; }[], packet: AedesPacket, cb: (error: Error | null | undefined) => void) => void.
    Types of parameters sub and subs are incompatible.
      Type { clientId: string | undefined; }[] is not assignable to type { clientId: string; }[].
        Type { clientId: string | undefined; } is not assignable to type { clientId: string; }.
          Types of property clientId are incompatible.
            Type string | undefined is not assignable to type string.
              Type undefined is not assignable to type string.  
```

**Comment by seriousme** [comment]
Well, my commit might have triggered it, but the commit only took the Subscription type from Aedes itself ;-)

Aedes defines Subscription as:
```javascript
export type Subscription = ISubscription & { clientId?: string }
```
See: https://github.com/moscajs/aedes/blob/00549ee41e29664265b9b03fbdb672b76647024b/types/packet.d.ts#L6

I can see that within Aedes functions a Subscription might not have a clientId yet (e.g. when parsing).
Ideally Aedes would export a `clientId` type  so that in `aedes-persistence` we can import it.

Happy to do a PR on Aedes types if you agree. 
If you don't agree then we just need to explictly redefine `clientId` as `string` in aedes-persistence.

Just let me know ;-)

Kind regards,
Hans
ps. we might want to tighten typechecking in CI just to avoid this on future commits ;-)
`

**Comment by robertsLando** [comment]
> Ideally Aedes would export a clientId type so that in aedes-persistence we can import it.

Ok :+1 Would also make sense to change ci to run `npm run test` instead `test:ci` to prevent this kind of errors in future

**Pull request merged**
